

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/opensource?useUnicode=true&amp;characterEncoding=UTF-8
  username: root
  password: 123456

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

  